version: '3.1'
services:
  stats-server:
    build: service-stats
    image: service_stats_image
    container_name: service_stats_container
    depends_on:
      - stats-db
    ports:
      - "9090:9090"

  stats-db:
    image: postgres:14-alpine
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewm-stats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  ewm-service:
    build: ewm-service
    image: ewm_service_image
    container_name: ewm-service
    depends_on:
      - ewm-db
    ports:
      - "8080:8080"

  ewm-db:
    image: postgres:14-alpine
