drop table if exists stat, app;

create table app
(
    id   bigint generated by default as identity
        primary key,
    name varchar(255)
);

create table stat
(
    id        bigint generated by default as identity
        primary key,
    ip        varchar(255),
    timestamp timestamp,
    url       varchar(255),
    app_id    bigint
        constraint app_fk
            references app
);
